[package]
name = "zdx-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
reqwest = "0.12.25"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
tracing = "0.1.43"

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
tempfile = "3.23.0"
wiremock = "0.6.5"
