[package]
name = "zdx-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.53"
reqwest = "0.12.25"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
tracing = "0.1.43"
